def list_methods():
    my_list=[1,2,3,4,5]
    print(my_list)
    my_list.append(6)
    print(my_list)
    my_list.extend([7,8,9])
    print(my_list)
    my_list.insert(2,10)
    print(my_list)
    my_list.remove(4)
    print(my_list)
    pop=my_list.pop(5)
    print(my_list)
def set_methods():
    my_set={1,2,3,4,5}
    print(my_set)
    my_set.add(6)
    print(my_list)
    my_set.remove(3)
    print(my_list)
    my_set.pop()
    print(my_list)
    my_set.discard(100)
    print(my_list)
    my_set.clear()
    print(my_list)
def tuple_methods():
    my_tuple=(1,2,3,4,5)
    print(my_tuple)
    my_tuple.index(5)
    print(my_tuple)